author: "Daniel Connelly"
email: "dhconnelly@gmail.com"

permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: ""

remote_theme: riggraz/no-style-please
theme_config:
    appearance: "light"
    date_format: "%Y-%m-%d"
    back_home_text: "[home]"
